name: ci

on:
    merge_group:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: ./.github/actions/setup

            - name: Run lint
              run: pnpm lint:ox --format github

            - name: Run prettier
              run: pnpm lint:prettier

            - name: Run typecheck
              run: pnpm typecheck

            - name: Run package
              run: pnpm package
